/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package footballmanager;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Yusuf
 */
public class Information extends JPanel {

    /**
     * Creates new form Information
     */
    public Information() {
        initComponents();
    }

    SamletPaneler ejer;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Information = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TekstInformation = new javax.swing.JTextArea();

        TekstInformation.setEditable(false);
        TekstInformation.setColumns(20);
        TekstInformation.setRows(5);
        TekstInformation.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TekstInformationAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(TekstInformation);

        Information.addTab("Information", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Information, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Information, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TekstInformationAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TekstInformationAncestorAdded

        TekstInformation.setText("");
        try {
            TekstInformation.append("Dit Hold Hedder: " + ejer.spil.getOwnTeamName());
        } catch (RemoteException ex) {
            Logger.getLogger(Information.class.getName()).log(Level.SEVERE, null, ex);
        }
        TekstInformation.append("\n");
        try {
            TekstInformation.append("\n" + "Din liga placering er på nuværende tidspunkt: " + (ejer.spil.getPosition()));
        } catch (RemoteException ex) {
            Logger.getLogger(Information.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_TekstInformationAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Information;
    private javax.swing.JTextArea TekstInformation;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
