/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package footballmanager;

import footballmanager.SamletPaneler;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Yusuf
 */
public class Kamp extends JPanel {

    SamletPaneler ejer;

    /**
     * Creates new form Kamp
     */
    public Kamp() {
        initComponents();
    }

    public void PlayedMatches() throws RemoteException {
        TextSpilleKampe.setText("");
        for (int i = 0; i < ejer.spil.SizeofplayedMatches(); i++) {
            TextSpilleKampe.append(ejer.spil.getMatch(i) + "\nResultat: " + ejer.spil.getResults(i) + "\n");
            if (i == 10 && ejer.spil.getFirsthalfseason() == true) {
                TextSpilleKampe.append("First half of the season has been played");
            }
            if (i == 21 && ejer.spil.getFirsthalfseason() == true) {
                TextSpilleKampe.append("Du kom på plads nummer " + ejer.spil.getPosition());
            }
        }
    }

    public void NextMatch() throws RemoteException {
        TextNæsteKamp.setText(ejer.spil.GetNextMatch());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TextSpilleKampe = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextNæsteKamp = new javax.swing.JTextField();
        KnapSpilNæsteKamp = new javax.swing.JButton();

        TextSpilleKampe.setColumns(20);
        TextSpilleKampe.setRows(5);
        jScrollPane2.setViewportView(TextSpilleKampe);

        jLabel1.setText("Spillede Kampe");

        jLabel2.setText("Næste kampe");

        TextNæsteKamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNæsteKampActionPerformed(evt);
            }
        });

        KnapSpilNæsteKamp.setText("Spil");
        KnapSpilNæsteKamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnapSpilNæsteKampActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextNæsteKamp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(KnapSpilNæsteKamp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextNæsteKamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KnapSpilNæsteKamp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextNæsteKampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNæsteKampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNæsteKampActionPerformed

    private void KnapSpilNæsteKampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnapSpilNæsteKampActionPerformed
        try {
            ejer.spil.MatchEngine();
            NextMatch();
            PlayedMatches();
            ejer.ShowLeague();
        } catch (RemoteException ex) {
            Logger.getLogger(Kamp.class.getName()).log(Level.SEVERE, null, ex);
        }

        

        /* try {
            ejer.spil.SaveFile();
        } catch (IOException e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_KnapSpilNæsteKampActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KnapSpilNæsteKamp;
    private javax.swing.JTextField TextNæsteKamp;
    private javax.swing.JTextArea TextSpilleKampe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
