/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package footballmanager;

import brugerautorisation.data.Bruger;
import brugerautorisation.transport.rmi.Brugeradmin;
import java.net.URL;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.Scanner;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;

public class SamletPaneler extends javax.swing.JPanel {

    FootballManagerI spil = null;

    public SamletPaneler() throws RemoteException {

        try {
            Registry registry = LocateRegistry.getRegistry("ubuntu4.javabog.dk", 53518);
            spil = (FootballManagerI) registry.lookup("FootballManagerI15351");
        } catch (Exception e) {
            e.printStackTrace();
        }

        initComponents();
        newGame2.ejer = this;
        kamp2.ejer = this;
        liga1.ejer = this;
        information1.ejer = this;
        holdPanel1.ejer = this;

        holdPanel1.Hold();

        int i = Tab.indexOfTab("Information");
        int k = Tab.indexOfTab("Kamp");
        int l = Tab.indexOfTab("Liga");
        int s = Tab.indexOfTab("Hold");

        Tab.setEnabledAt(i, false);
        Tab.setEnabledAt(k, false);
        Tab.setEnabledAt(l, false);
        Tab.setEnabledAt(s, false);

    }

    public void MakeLeague() throws RemoteException {
        spil.CreateLiga();
        ShowLeague();
    }

    public void ShowLeague() throws RemoteException {
        liga1.League();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matchEngine1 = new footballmanager.MatchEngine();
        matches1 = new footballmanager.Matches();
        Tab = new javax.swing.JTabbedPane();
        newGame2 = new footballmanager.NewGame();
        kamp2 = new footballmanager.Kamp();
        liga1 = new footballmanager.Liga();
        holdPanel1 = new footballmanager.HoldPanel();
        information1 = new footballmanager.Information();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(new java.awt.BorderLayout());

        Tab.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TabAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Tab.addTab("New Game", newGame2);
        Tab.addTab("Kamp", kamp2);
        Tab.addTab("Liga", liga1);
        Tab.addTab("Hold", holdPanel1);
        Tab.addTab("Information", information1);

        add(Tab, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void TabAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TabAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TabAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane Tab;
    public footballmanager.HoldPanel holdPanel1;
    public footballmanager.Information information1;
    public footballmanager.Kamp kamp2;
    public footballmanager.Liga liga1;
    private footballmanager.MatchEngine matchEngine1;
    private footballmanager.Matches matches1;
    private footballmanager.NewGame newGame2;
    // End of variables declaration//GEN-END:variables
}
